### ISSUE TITLE
Unable to create a new app with vs2019 and latest version of catel project template

### ISSUE THREAD

**Issue by ghost** [Catel/Catel.Templates#12]
I tried to create a project with VS2019 and new version of project template, but it seams something wrong with that template. I couldn't create a project. I get always an error from VS: "one o more errors occurred"
### Steps to reproduce

1. Install the project template for catel wpf application.
2 try to create an app with vs2019.

**Comment by lex-f** [comment]
I have similar problem. 
But i also have vs2017. and there I have installed "catel wpf application" version 5.0 and 5.1.0.16. 
5.0 work great, 5.1 - have error "the project is not complete. no expected operator imports".
i just replace file "Catel.WPF.Application.csproj" from directory version 5.0 to version 5.1 and 5.1 strated up.
I don’t know how right it is. but apparently the problem is related to "MSBuild.Sdk.Extras"?
maybe you tell me how to do it right?

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, we will try to fix this as soon as we have resources / time available. Did you check the readme that's generated?

**Comment by lex-f** [comment]
Readme generated from 5.1 template folder. Now i use "Catel.WPF.Application.csproj" from version 5.0 and manual install needed PackageReference (catel, fody etc.). And this way work normall.

**Comment by GeertvanHorrik** [comment]
I think I found the issue. It's the custom sdk version without versioning. Will push / release a fix asap.

**Comment by GeertvanHorrik** [comment]
Releasing a fix. If the issue still persist, feel free to re-open the ticket.

**Comment by GeertvanHorrik** [comment]
See https://marketplace.visualstudio.com/items?itemName=Catel.Catel-ProjectTemplates-WPF-Application
